//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfoDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbleTB
    {
        public int learnerId { get; set; }
        public string learnerName { get; set; }
        public string favoriteTeacher { get; set; }
        public Nullable<int> coursesRemaining { get; set; }
        public Nullable<int> coursesCompleted { get; set; }
    }
}
